### ISSUE TITLE
For inline comments, double brackets rule may be redundant

### ISSUE THREAD

**Issue by kevinschaul** [newsdev/archieml.org#15]
I'm not sure if the following is intended behavior. Take the following ArchieML example:

```
key: this is a \[very important\] value
```

Currently the result is:

```
{
  "key": "this is a \\ value"
}
```

Is that intended? I would imagine that using backslashes would escape the brackets, resulting in:

```
{
  "key": "this is a [very important] value"
}
```

This behavior would make the [[double brackets]] to preserve a single set rule redundant.

**Comment by abstrctn** [comment]
So brackets are handled idiosyncratically in archieml (your second code block is the expected behavior).

For most of the language, there is only one situation in which you need to escape something: when you're writing a multi-line value, and you want to start one of those lines with a "special" token. At the same time, we wanted to avoid teaching non-programmers an escape character.

A middle ground was escaping whole lines instead of characters, the thinking being that it's easier to teach someone to add a `\` to the start of the line, than teaching them to add it in front of the `:` in these two examples:

Instead of this:

```
key: value
key\: end
\:end
:end
```

This:

```
key: value
\key: end
\:end
:end
```

That method breaks down for double brackets, but I still think it'd be nice to keep escape characters out of the picture if possible.

In practice, we've found that we almost never use inline comments, leading to [this branch](https://github.com/newsdev/archieml-js/tree/feature/optional-comments) which lets you turn off the regexes that remove single brackets, and replace double brackets with single brackets. If you want, try using that branch, and we can merge it in barring any changes you'd like to see.

**Comment by kevinschaul** [comment]
Ah, I see. That makes sense.

I think there is still a minor issue with my proposed example. Shouldn't the output only have a single backslash since everything inside of brackets is treated as a comment?

```
{
  "key": "this is a \ value"
}
```

I don't mean to nit pick, just hoping to fully understand.

**Comment by abstrctn** [comment]
Not nit picking at all - I wondered the same thing when I read your example, and plugged it in to the [sandbox](http://archieml.org/sandbox.html). The two backslashes you're seeing is actually one backslash (the initial one), that has itself been escaped with a backslash as part of `JSON.stringify`. The second backslash has been removed, as it's inside the single brackets.

You can see this by including a single backslash as part of a value:

```
key: \
```

```
{
  "key": "\\"
}
```

---

To avoid confusion as you're testing, I also noticed a bug in the current implementation. It looks like `key: \[]` winds up as `{ "key": "" }`, which is incorrect, because backslashes aren't supposed to be parsed as escapes at all on the first line of a value. The value should end up as a single backslash, or `\\` when it's escaped by the stringify output.

**Comment by kevinschaul** [comment]
Didn't realize JSON.stringify escaped backslashes. Got it. Thanks for walking me through it.
